name: Selenium Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest # Uses a fresh Ubuntu virtual machine for the job

    steps:
    - uses: actions/checkout@v4 # Action to check out your repository code
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Action to set up the Java environment
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven